### PR TITLE
added product landing page folder

### PR DESCRIPTION
**Pull request by Aldhanekaa**
[Demo](https://product-landing-page-blue.vercel.app/)
note: this website is not responsive

### CODE REVIEW

**Comment by Aldhanekaa** [comment]
#1

**Comment by Aldhanekaa** [comment]
Oops looks like this is not a portfolio website..

**Comment by Aldhanekaa** [comment]
Hi @hambali999, thank you for merged this PR! However, can you label this PR as ``hacktoberfest-accepted``? 
It's a new rule from hacktoberfest, If the PR not labeled as ``hacktoberfest-accepted`` my PR will not count.

[More Information about new updates](https://hacktoberfest.digitalocean.com/hacktoberfest-update)
Thank you!

**Comment by hambali999** [comment]
> Hi @hambali999, thank you for merged this PR! However, can you label this PR as `hacktoberfest-accepted`?
> It's a new rule from hacktoberfest, If the PR not labeled as `hacktoberfest-accepted` my PR will not count.
> 
> [More Information about new updates](https://hacktoberfest.digitalocean.com/hacktoberfest-update)
> Thank you!

Done !

**Pull request merged**
